//The server will maintain a list of all 
	//connected clients (host names) 
	//list together the number of requests generated by each client 
	//the amount of data transferred to each client.  
//Each client will also maintain a record of 
	//how many requests made to server
	//amount of data sent to server
	//amount of time it took for the server to respond (i.e., echo the data back).  
//hashmap to store information. write to file on program exit to avoid multiple threads writing to file
	//https://github.com/kshk123/hashMap/blob/master/inc/HashMap.h
		//server: key IP(of client),Value {requests, data}
		//client: key IP(of server),Value {requests, timeAVG}
void list(){}